- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli
  tasks:
    - name: Generate Template for Device
      template: src="{{config_template}}" dest="{{config_path}}{{hostname}}.conf" mode='0777'
